### ISSUE TITLE
[Docs] 팀 노션 만들기

### ISSUE THREAD

**Issue by kimseungdeok** [Sail365/Tab-line#5]
## Description
설명을 작성하세요.
- 서비스 제작을 위한 노션 만들기
- 회의 내용 정리, 일정 정리 등등을 노션을 통해 하면 좋을듯합니다
- 📆 2월 28일까지 만들도록 해보겠습니다.

## To-do
- [ ] 노션 만들기

## ETC
기타 사항을 작성하세요
- 의견이 있으면 코멘트 주시면 감사하겠습니다! 🫡

**Comment by Louis-Gil** [comment]
노션 오케이!

**Comment by kimseungdeok** [comment]
https://www.notion.so/Team-Sail-365-b36c56088dd245eca0933ca5128f5e5f
