### ISSUE TITLE
[Feature] DB 연결

### ISSUE THREAD

**Issue by Louis-Gil** [Sail365/Tab-line#8]
## Description
DB 서버 연결

## To-do
- [x] DB 서버 생성
- [x] DB 연결

## ETC
기타 사항을 작성하세요
의견 공유바랍니다.

**Comment by kimseungdeok** [comment]
방금 슬랙에서 말씀하신것처럼 **mongoDB**가 저희 서비스에 적절한것같습니다 ㅎㅎ
